# Generated by Django 4.0.2 on 2022-03-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_documents_expenses_extrahour_extrahourhistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrahour',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='extrahourhistory',
            old_name='user',
            new_name='user_id',
        ),
    ]
