# Generated by Django 4.0.2 on 2022-03-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_rename_user_id_extrahour_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrahourhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
